# Import shared constants from base module
from Modules.base.constants import (
    CLEANUP_TIMEOUT_SECONDS,
    DEVICE_DISCOVERY_TIMEOUT_SECONDS,
    DEVICE_DISCOVERY_RETRY_SECONDS,
    MAX_ERROR_MESSAGE_LENGTH,
    KEYBOARD_POLL_INTERVAL,
)

FPS_MIN = 1.0
FPS_MAX = 120.0
FPS_DEFAULT = 5.0

RESOLUTION_WIDTH_MIN = 320
RESOLUTION_WIDTH_MAX = 3840
RESOLUTION_HEIGHT_MIN = 240
RESOLUTION_HEIGHT_MAX = 2160
RESOLUTION_DEFAULT = (1280, 720)

PREVIEW_WIDTH_MIN = 320
PREVIEW_WIDTH_MAX = 1920
PREVIEW_WIDTH_DEFAULT = 640

# Module-specific timeouts
STREAM_STOP_TIMEOUT_SECONDS = 5.0
FRAME_TIMEOUT_SECONDS = 1.0

FRAME_PROCESS_INTERVAL = 0.0  # asyncio.sleep(0) for cooperative multitasking

RECORDING_FORMAT_MP4 = "mp4"
RECORDING_FORMAT_AVI = "avi"
RECORDING_CODEC_H264 = "H264"
RECORDING_CODEC_MJPEG = "MJPEG"

GAZE_QUEUE_SIZE = 100
IMU_QUEUE_SIZE = 100
EVENT_QUEUE_SIZE = 100
FRAME_QUEUE_SIZE = 10

STATUS_UPDATE_INTERVAL_SECONDS = 2.0

WINDOW_NAME_PREFIX = "Eye Tracker"

FRAME_WARNING_INTERVAL = 5  # Log frame warnings every N seconds
