from typing import Protocol, AsyncIterator, runtime_checkable

from .frame import CapturedFrame


@runtime_checkable
class FrameSource(Protocol):
    async def start(self) -> None: ...
    async def stop(self) -> None: ...
    def frames(self) -> AsyncIterator[CapturedFrame]: ...

    @property
    def is_running(self) -> bool: ...

    @property
    def hardware_fps(self) -> float: ...

    @property
    def frame_count(self) -> int: ...

    @property
    def drop_count(self) -> int: ...
