#!/usr/bin/env python3

SAMPLE_RATE_MIN = 8000
SAMPLE_RATE_MAX = 192000
SAMPLE_RATE_DEFAULT = 48000

AUDIO_DTYPE = 'float32'
AUDIO_CHANNELS_MONO = 1
AUDIO_BIT_DEPTH = 16

AUDIO_BLOCKSIZE = 1024
FEEDBACK_QUEUE_SIZE = 100
FEEDBACK_INTERVAL_SECONDS = 2.0
MAX_AUDIO_BUFFER_CHUNKS = 10000  # Max chunks before warning (prevents unbounded growth)

CLEANUP_TIMEOUT_SECONDS = 2.0
DEVICE_DISCOVERY_TIMEOUT = 5.0
DEVICE_DISCOVERY_RETRY = 3.0
STREAM_STOP_TIMEOUT_SECONDS = 3.0

USB_POLL_INTERVAL = 0.005
KEYBOARD_POLL_INTERVAL = 0.001

MAX_ERROR_MESSAGE_LENGTH = 200

WAV_COMPRESSION_NONE = 0
