#!/usr/bin/env python3

# Import shared constants from base module
from Modules.base.constants import (
    CLEANUP_TIMEOUT_SECONDS,
    DEVICE_DISCOVERY_TIMEOUT_SECONDS,
    DEVICE_DISCOVERY_RETRY_SECONDS,
    MAX_ERROR_MESSAGE_LENGTH,
    KEYBOARD_POLL_INTERVAL,
)

SAMPLE_RATE_MIN = 8000
SAMPLE_RATE_MAX = 192000
SAMPLE_RATE_DEFAULT = 48000

AUDIO_DTYPE = 'float32'
AUDIO_CHANNELS_MONO = 1
AUDIO_BIT_DEPTH = 16

AUDIO_BLOCKSIZE = 1024
FEEDBACK_QUEUE_SIZE = 100
FEEDBACK_INTERVAL_SECONDS = 2.0
MAX_AUDIO_BUFFER_CHUNKS = 10000  # Max chunks before warning (prevents unbounded growth)

# Module-specific timeouts
STREAM_STOP_TIMEOUT_SECONDS = 3.0

USB_POLL_INTERVAL = 0.005

WAV_COMPRESSION_NONE = 0
